export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_USERS_LOCATION_WEATHER = 'GET_USERS_LOCATION_WEATHER';
export const GET_USERS_LOCATION = 'GET_USERS_LOCATION'